# Generated by Django 3.2 on 2021-04-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
            ],
            options={
                'verbose_name': 'ゲスト',
                'verbose_name_plural': 'ゲスト一覧',
                'db_table': 'guest',
            },
        ),
    ]
